package com.zerovoid.main;

public class Test2 {
	public static void main(String[] args) {
		String s = "{"
				+ "   \"errInfo\": \"OK\",\n"
				+ "   \"entity\":    {\n"
				+ "      \"orderStatus1\": \"买家已付款\",  --'订单状态'\n"
				+ "      \"orderStatus\": \"1\",  --'订单状态(0待付款；1已付款；2已发货；3已完成;4已取消；5支付中;6取消订单；7申请退款；8已退款)'\n"
				+ "      \"phone\": \"\",\n"
				+ "      \"totalCost\": 12,  --'总金额'\n"
				+ "      \"remark\": \"\",  --'备注'\n"
				+ "      \"shipName\": \"打给\",  --'收货人'\n"
				+ "      \"couponValue\": \"\", --'抵用金额'\n"
				+ "      \"payTime\": 1450429145000,  --'支付时间'\n"
				+ "      \"refundTime\": \"\",  --'退款时间'\n"
				+ "      \"orderInfo\": \"\",\n"
				+ "      \"linkID\": \"\",\n"
				+ "      \"shipTypes\": \"到店提货\",  --'配送方式'\n"
				+ "      \"shipType\": \"2\",  --'配送方式（1邮寄，2到店提货，3送货上门）'\n"
				+ "      \"pics\": \"\",\n"
				+ "      \"applyRefundTime\": \"\",  --'申请退款时间'\n"
				+ "      \"goodsCost\": 12,   --'商品金额'\n"
				+ "      \"merchantName\": \"烤鱼\",   --'商家名'\n"
				+ "      \"tsedit\": 1450429150000,\n"
				+ "      \"goodsInfo\": [      {\n"
				+ "         \"title\": \"1111\",              --'标题'\n"
				+ "            \"cover\": \"http://7te8s5.com2.z0.glb.qiniucdn.com/web_1448893867513247.png\",  --'图片'\n"
				+ "            \"price\": 1,     --'市场价格'\n"
				+ "            \"sellPloyID\": \"15c9d5df-1152-47f2-a232-d303ccaa76c8\",  --'策略ID'\n"
				+ "            \"goodsCount\": \"1\",  --'策略ID'\n"
				+ "            \"pdtDesc\": \"12kg\",  --'规格'\n"
				+ "            \"mkPrice\": 1,    --'原价'\n"
				+ "            \"productID\": \"6bd21a7d-22e3-42f1-a63e-8c9479ea48a9\",   --'产品ID'\n"
				+ "            \"goodsName\": \"1111\"  --'商品名'\n"
				+ "      }],\n"
				+ "      \"refundMoney\": \"\",  --'退款金额'\n"
				+ "      \"comm\": \"小区2\",  --'小区'\n"
				+ "      \"tscreate\": 1450429133000,\n"
				+ "      \"shipPhone\": \"18050274981\",  --'收货人电话'\n"
				+ "      \"orderID\": \"14504291328471929\",  --'订单ID'\n"
				+ "      \"couponName\": \"\",  --'抵用劵名称'\n"
				+ "      \"payName\": \"余额支付\",  --'支付方式'\n"
				+ "      \"orderType\": \"14\",  --'订单类型(1商品;2活动;3团购,4维修,5清洁,6充值,7积分兑换,8物业费,9停车费,10估价单,11定价单12钟点工订单13停车卡14周边乐购)'\n"
				+ "      \"deliverGoodsTime\": \"\",  --'发货时间'\n"
				+ "      \"shipAddr\": \"福建省福州市鼓楼区春节后隔壁\",  --'收货地址'\n"
				+ "      \"logisticsCompany\": \"\",  --'物流公司'\n"
				+ "      \"orderTime\": 1450429133000,  --'下单时间'\n"
				+ "      \"shipCost\": 0,  --'邮费'\n"
				+ "      \"payStatus\": \"已支付\",   --'支付状态'\n"
				+ "      \"orderNumber\": 1,  --'购买数量'\n"
				+ "      \"logisticsID\": \"\"  --'物流单号'\n" + "   },\n"
				+ "   \"errCode\": 0\n" + "}";
		String replaceAll = s.replaceAll("--.*", " ");
		System.out.println(replaceAll);
	}
}
